### ISSUE TITLE
Could not load js config file $folder/node_modules/@_sh/strapi-plugin-ckeditor/strapi-server.js: Unexpected token '?'

### ISSUE THREAD

**Issue by signorekai** [nshenderov/strapi-plugin-ckeditor#23]
Installing the plugin on `strapi@4.1.8` running `node v12.22.12 (lts)` and after building the admin UI via `npm run build`, I'm unable to start the strapi server with `npm run dev`.

```
[2022-07-25 15:01:45.839] debug: ⛔️ Server wasn't able to start properly.
[2022-07-25 15:01:45.841] error: Could not load js config file $folder/node_modules/@_sh/strapi-plugin-ckeditor/strapi-server.js: Unexpected token '?'
Error: Could not load js config file $folder/node_modules/@_sh/strapi-plugin-ckeditor/strapi-server.js: Unexpected token '?'
    at loadJsFile ($folder/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile ($folder/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins ($folder/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:96:26)
    at async Strapi.loadPlugins ($folder/node_modules/@strapi/strapi/lib/Strapi.js:284:5)
    at async Promise.all (index 1)
    at async Strapi.register ($folder/node_modules/@strapi/strapi/lib/Strapi.js:316:5)
    at async Strapi.load ($folder/node_modules/@strapi/strapi/lib/Strapi.js:414:5)
    at async Strapi.start ($folder/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
```

**Comment by signorekai** [comment]
Figured out the issue; apparently the plugin doesn't support node v12? I updated to `v14.9.1` and it's working properly now. Might want to add it to the requirements?
