### ISSUE TITLE
installation error "path" argument undefined

### ISSUE THREAD

**Issue by BrettBedarf** [nshenderov/strapi-plugin-ckeditor#8]
Hi, I'm trying to install following the provided instructions.

`yarn add @_sh/strapi-plugin-ckeditor`

```
// config/plugins.js

module.exports = () => {
    return {
        ckeditor: true
    }
}
```

`strapi dev`

```
strapi:dev: cc_strapi             | [2022-05-21 22:18:14.292] debug: ⛔️ Server wasn't able to start properly.
strapi:dev: cc_strapi             | [2022-05-21 22:18:14.293] error: The "path" argument must be of type string. Received undefined
strapi:dev: cc_strapi             | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
strapi:dev: cc_strapi             |     at new NodeError (node:internal/errors:372:5)
strapi:dev: cc_strapi             |     at validateString (node:internal/validators:120:11)
strapi:dev: cc_strapi             |     at join (node:path:1172:7)
strapi:dev: cc_strapi             |     at Object.loadPlugins (/app/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:89:34)
strapi:dev: cc_strapi             |     at async Strapi.loadPlugins (/app/node_modules/@strapi/strapi/lib/Strapi.js:284:5)
strapi:dev: cc_strapi             |     at async Promise.all (index 1)
strapi:dev: cc_strapi             |     at async Strapi.register (/app/node_modules/@strapi/strapi/lib/Strapi.js:316:5)
strapi:dev: cc_strapi             |     at async Strapi.load (/app/node_modules/@strapi/strapi/lib/Strapi.js:414:5)
strapi:dev: cc_strapi             |     at async Strapi.start (/app/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
strapi:dev: cc_strapi exited with code 1
```

**Comment by BrettBedarf** [comment]
nevermind this has something to do with my docker setup as I can build and run outside of a container with the plugin
